logging:
  level:
    root: info
    org.mariadb.SQL: debug
    #org.hiberante.type: trace - 스프링부트 3.0, Hibernate 6.0미만 버전
    org.mariadb.orm.jdbc.bind: trace
    org.apache.coyote.http11: debug #Http 요청정보 로그 남기기
      #spring.servlet.multipart.max-file-size=2MB                        #하나의 파일 최대 크기
      #spring.servlet.multipart.max-request-size=5MB                   #전체 보내는 파일의 총 크기 제한
      #spring.servlet.session.tracking-modes=cookie
      #logging.level.mvc.study=info

spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/board_study
    username: root
    password: 1234
    driver-class-name: org.mariadb.jdbc.Driver

mariadb:
  console:
    enable: true
    path: /mariadb-console

jpa:
  show-sql: true
  open-in-view: false
  database0platform: org.mariadb.dialect.MariaDBDialect
  properties:
    mariadb:
      format_sql: true
      highlight_sql: true
      use_sql_comments: true
      default_batch_fetch_size: 100

      mariadb:
        ddl-auto: create
      data:
        web:
          pageable:
            default-page-size: 20
server:
  port: ${myapp.port:8888}

